twig:
    file_name_pattern: '*.twig'
#    form_themes:
#        [ 'bootstrap_5_layout.html.twig']
    globals:
        images: '%relative_img_dir%'

when@test:
    twig:
        strict_variables: true
