<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '60f0fccb05851eb6976348b9c477a087',
  'DATABASE_URL' => 'mysql://root:root@mysql:3306/symf6-hands-on?serverVersion=8.0&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://0.0.0.0:1025',
  'NGINX_PORT' => '17000',
  'ADMINER_PORT' => '17003',
  'XDEBUG_PORT' => '9003',
  'FPM_PORT' => '17005',
  'DB_USER' => 'root',
  'DB_PASSWORD' => 'root',
  'DB_HOST' => 'mysql',
  'PROJECT_NAME' => 'symfony-test',
);
