version: "3.8"
services:
  php:
    build:
     dockerfile: ./infrastructure/Dockerfile
#    environment:
    volumes:
      - ./:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx.conf.d/default.conf
      - ./:/.app
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
