controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

health_check:
    path: /health
    controller: Api\Actions
#app_index:
#    path: /
#    controller: App\Controller\HomePageController::index
#app_show:
#    path: /show/{id?}
#    controller: App\Controller\HomePageController::show